x-common-volumes: &common-volumes
  - ./:/textToVideoGeneration

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "textToVideoGeneration-webui"
    ports:
      - "8501:8501"
    command: [ "streamlit", "run", "./webui/Main.py","--browser.serverAddress=127.0.0.1","--server.enableCORS=True","--browser.gatherUsageStats=False" ]
    volumes: *common-volumes
    restart: always
